spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: true
    generate-ddl: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  application:
    name: Neoris
logging:
  level: 
    root: INFO